--- 
title: "Community contributions for STAT GR 5702 Fall 2019" 
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: skyetim/edav_community_contribution_dev
description: "This book will hold all community contributions for STAT GR 5702 Fall 2019 at Columbia University"
---

# cc19
Community contributions for STAT GR 5702 Fall 2019

The class projects will be collected as a bookdown page. Similar to edav.info (https://edav.info/), the chapters on the left panel link to each of the student projects.


## Setup

1. Fork the cc19 repo (at https://github.com/jtr13/cc19). More information about how to achieve this on https://edav.info/github.html#branching-someone-elses-repo.

2. Clone/download the repo to your local computers.

3. Create a folder (one is needed for a project) and give it a concise, descriptive name. For instance, name it `base_r_ggplot_graph` or sonething similar if your work is about constrasting/working with base R graphics and GGplot graphics. **No whitespace in the name.** 



## Important

1. Please also create your project page in .rmd file with the following modification before submission:

* Remove the YAML header
* Put your project name in the first line. This does not have to be exact same as the project folder name. Using one \# to indicate that it is a header. One \# must not be used else where in the document. If you need to bold the text, use more than one \#s. For example,

      # Base R graphics vs. GGplot graphics
      
* Leave the second line empty

2. Do not make any changes outside your folder. If you do accidentally, do not commit those changes.



## Submission

When you are ready to submit your project, push your project folder to your remote repo. And follow *creating a pull request from a fork* (https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) to create a pull request. If there is no conflict, it will be merge to the class repo.

<!--chapter:end:index.Rmd-->

