# Hex Sticker

Priyadharshini Rajbabu and Suman Tripathy

Our group was tasked with designing a hex sticker for the EDAV course, under the advisement of Professor Robbins.

We were initially provided with a folder of various logos used on the edav.info webpage. They can be found at this link <https://github.com/jtr13/EDAV/tree/master/images/icons>.

We first considered using the hexSticker package in R to create a hex sticker design, but ran into issues with image quality on the sticker and also felt there were limited resources for design with this package. 

A better alternative was to use Adobe Photoshop to design the sticker with the help of a blank psd template from Sticker Mule, to set up the proper sizing and to allow for easy printing. 

Some things we took into consideration in detail while designing the sticker were:

1. Color scheme of the sticker:
- Decided to stick to the shade of blue widely used on edav.info webpage.
- After much experimentation, we converted the icons and logos to an all-black theme, which better complemented the blue. 

2. Cropping the edav.info logo:
- We cut out the ".info" half of the initial logo for this sticker. The technique to doing this in photoshop was to erase this half and set it to a transparent background, allowing the blue background to take its place. 

3. Ordering of the three elements of the sticker:
- We experimented with quite a few variations of the sticker to see what layout/ordering of the edav icon, logo, and "fall 2019" title would be most compatible. 

The sticker has been saved in a photoshop (psd) file, as that is where we designed it. 

PSD FILE -> <https://github.com/prajbabu/edavhex/blob/master/edavhexsticker.psd>

For readability, and for those who don't have Adobe Photoshop installed, the file has also been saved as a: 

PDF -> <https://github.com/prajbabu/edavhex/blob/master/edavhexstickerFINAL.pdf> 

PNG -> <https://github.com/prajbabu/edavhex/blob/master/hexsticker_image.png>. 

* If hyperlinks don't work, please copy link into a browser.*
