# List of Community Contribution

Kevin Gao (wg2311) and Haibo Yu (hy2628)

We have tried many different things from the list, including:

### * A lighting talk in class

  Title: Experiments Tool and Visualization
  
  Description: The "Virtual Lab" refers to using software controlled experiments with internet participants to overcome many of the limitations of traditional lab experiments. To help researchers study more complex tasks and set up interactions that happen over longer periods of time or among larger numbers of people. This allows us to design behavioral experiments and visualize data that would have been very hard to do in the past. I would like to share some of the work and how we visualize things to make a difference.

### * A cheatsheet 

  About mapping grammar for ggplot2,pyplot,d3 

### * A series of tutorials

  About how to share your R work (4 ways):
  
  1. Publish and share your R plots, hosted free in github [website](https://columbia-dsi.github.io) (Quick, Simple and Free)
  2. Release R Package, through cran or github
  3. Deploy R model to Azure ML Studio (The Simplest Way)
  4. Deploy R model as Web Service (The Structured Way)

### * A workshop - "ShareYouRWork"

  Give a walkthough demo on how to deploy R model as web service. (The Structed Way)


For more information, please visit our github main repo [here](https://github.com/columbia-dsi/edav_community)